spring:
  application:
    name: CalculadorMIcroServices

feign:
  client:
    calcRepo:
      url: "http://localhost:8081/api/v1/calcRepo"

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true
